# Generated by Django 5.1.7 on 2025-08-05 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="businessinfo",
            name="about_us",
            field=models.TextField(
                default="默认公司介绍内容...", verbose_name="公司介绍"
            ),
        ),
        migrations.AddField(
            model_name="businessinfo",
            name="cta_text",
            field=models.TextField(
                default="Avoid the stress and complexity of international shipping!",
                verbose_name="联系区域文本",
            ),
        ),
        migrations.AddField(
            model_name="businessinfo",
            name="hero_subtitle",
            field=models.TextField(
                default="Need fast and reliable shipping for your goods? Whether it's air, road, or sea - we've got you covered!",
                verbose_name="首页副标题",
            ),
        ),
        migrations.AddField(
            model_name="businessinfo",
            name="hero_title",
            field=models.CharField(
                default="FREIGHT SOLUTIONSEXPRESS PTY LTD",
                max_length=200,
                verbose_name="首页标题",
            ),
        ),
    ]
