# Generated by Django 5.1.7 on 2025-08-05 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_businessinfo_about_us_businessinfo_cta_text_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="businessinfo",
            options={
                "verbose_name": "网站基础信息",
                "verbose_name_plural": "网站基础信息",
            },
        ),
        migrations.RemoveField(
            model_name="contactsubmission",
            name="email",
        ),
        migrations.RemoveField(
            model_name="contactsubmission",
            name="message",
        ),
        migrations.RemoveField(
            model_name="contactsubmission",
            name="phone",
        ),
        migrations.AddField(
            model_name="contactsubmission",
            name="additional_notes",
            field=models.TextField(
                blank=True, null=True, verbose_name="Additional Notes"
            ),
        ),
        migrations.AddField(
            model_name="contactsubmission",
            name="dropoff_location",
            field=models.CharField(
                default="", max_length=200, verbose_name="Dropoff Location"
            ),
        ),
        migrations.AddField(
            model_name="contactsubmission",
            name="load_size",
            field=models.CharField(
                default="", max_length=100, verbose_name="Load Size"
            ),
        ),
        migrations.AddField(
            model_name="contactsubmission",
            name="load_weight",
            field=models.CharField(
                default="", max_length=50, verbose_name="Load Weight (approx)"
            ),
        ),
        migrations.AddField(
            model_name="contactsubmission",
            name="phone_email",
            field=models.CharField(
                default="", max_length=100, verbose_name="Phone / Email"
            ),
        ),
        migrations.AddField(
            model_name="contactsubmission",
            name="pickup_location",
            field=models.CharField(
                default="", max_length=200, verbose_name="Pickup Location"
            ),
        ),
        migrations.AddField(
            model_name="contactsubmission",
            name="preferred_datetime",
            field=models.CharField(
                default="", max_length=100, verbose_name="Preferred Date/Time"
            ),
        ),
    ]
